### PR TITLE
Fix #388

### LINKED ISSUE #388: Some Static Groups do have more than one static unit
### Brief Description: 
Create an objective, set its task target as structures (any, military, production, offshore) with a Target count of very high.
There is a chance that the static group will be something like Outpost, which is only configured with one building, which is not a very high target count.

### Expected: 
Should get a grouping of units such as a couple of buildings/gas tanks

After debugging, it looks like there is a drop in connection between the configured min,max target count configured for a given ObjectiveTarget ini file such as in Database/ObjectiveTargets/StructureMilitary.ini
If I configure that file to have a VeryHigh min-max of 8,12 when generating the mission only sometimes will I get a group of buildings that actually has more than one building.

This is caused in two part I think. 
1) DBEntryCoalition.GetRandomUnits will modify the unit count to one because it understands correctly that a group of statics in dcs can only be a single static, however this is now a regression with the #288 behavior because although dcs groups are size one, we can place multiple statics at a single objective.

2) This is the reason 1 is important with my limited understanding. During the creation of a Static group in UnitMaker.AddStaticGroup, it has no knowledge of how many buildings the user had requested with the TargetCount field.

On the surface, a simple solution would be to count how many units are in a staticgroup and only spawn that static group if it meets the min-max requirements set by the user.... Trouble with this is that staticgroups have a fixed amount of statics, and this may not exactly match the unit count ask exactly, or no groups may exist within a range.

Probably a good idea would be to have some sort of fuzzy understanding of the TargetCount of a given static group and match that with the users request.
I think something like a min max value that measures how many statics are in the configured groups. and then divides the difference by the amount of possible TargetCount values the user can request (5 currently) giving 5 ranges of static count and grouping the configured static groups would work as a "fuzzy understanding"

EX: the static groups for FARP and Ammo Depos would fall into the VeryHigh target count category

I will probably hack together my hairbrained scheme and if its clean enough I can send in a PR

### PR DESCRIPTION
**Pull request by NovaLogicDev**
Attempt to address #388

### CODE REVIEW

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 1]
```diff
@@ -120,20 +126,60 @@ protected override bool OnLoad(string iniFilePath)
...
+                while (!(validUnits_GroupSizeBetweenMin_and_Max[country].Count > 0));
+                    
+            }
+
+
+            if (validUnits_GroupSizeBetweenMin_and_Max.Count > 0)
+                return validUnits_GroupSizeBetweenMin_and_Max;
+
+            BriefingRoom.PrintToLog($"No Units found that exceed requested TargetCount", LogMessageErrorLevel.Error);
+            throw new Exception("Requested Target Count greater than Maximum Configured Target Count"); //TODO: Unhandled
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:156]: [suggestion] if valid unit count is 0 then throw error
[issue] Use `BriefingRoomException` its handled

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 2]
```diff
@@ -120,20 +126,60 @@ protected override bool OnLoad(string iniFilePath)
...
+        }
+
+        private List<string> LimitValidUnitsByMinMax(List<(string, int)> validUnitsIDs_and_Lengths, int minUnitCount, int maxUnitCount)
+        {
+            return (
+                from (string, int) unit in validUnitsIDs_and_Lengths
+                where unit.Item2 >= minUnitCount && unit.Item2 <= maxUnitCount
+                select unit.Item1
+                ).ToList();
+        }
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:166]: [issue] Ref LINQ query suggestion above this can now just be a bool response

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 3]
```diff
@@ -92,15 +92,22 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
             var luaUnit = targetBehaviorDB.UnitLua[(int)targetDB.UnitCategory];
             Coordinates objectiveCoordinates = GetSpawnCoordinates(template, lastCoordinates, playerAirbase, targetDB);
 
-            // Spawn target on airbase
             var unitCount = targetDB.UnitCount[(int)objectiveTemplate.TargetCount].GetValue();
+            var maxUnitCount = targetDB.UnitCount[(int)objectiveTemplate.TargetCount].Max;
+            var minUnitCount = targetDB.UnitCount[(int)objectiveTemplate.TargetCount].Min;
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:97]: [nitpick] No need for this as `targetDB.UnitCount[(int)objectiveTemplate.TargetCount]` is an object where you can pull min & max cleaner.

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 4]
```diff
@@ -92,15 +92,22 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
...
             var objectiveTargetUnitFamily = Toolbox.RandomFrom(targetDB.UnitFamilies);
+            
+            // Spawn target on airbase
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:100]: [nitpick] no need for comments here

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 5]
```diff
@@ -92,15 +92,22 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
...
             if (AIRBASE_LOCATIONS.Contains(targetBehaviorDB.Location) && targetDB.UnitCategory.IsAircraft())
                 objectiveCoordinates = PlaceInAirbase(template, situationDB, playerAirbase, extraSettings, targetDB, targetBehaviorDB, ref luaUnit, objectiveCoordinates, unitCount, objectiveTargetUnitFamily);
 
             UnitMakerGroupFlags groupFlags = 0;
+
+            // Set whether or not the Objective is Hidden.. options: Never OR Always
             if (objectiveOptions.Contains(ObjectiveOption.ShowTarget)) groupFlags = UnitMakerGroupFlags.NeverHidden;
             else if (objectiveOptions.Contains(ObjectiveOption.HideTarget)) groupFlags = UnitMakerGroupFlags.AlwaysHidden;
+
+            // Set if Objective has Embedded Air Defense
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:110]: [nitpick] no need for comments here

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 6]
```diff
@@ -116,6 +123,8 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
 
             var unitCoordinates = objectiveCoordinates;
             var objectiveName = Toolbox.RandomFrom(ObjectiveNames);
+
+            // Determine if Transport Task, if so do things
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:127]: [nitpick] no need for comments here

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 7]
```diff
@@ -140,7 +149,7 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
             extraSettings.Add("GroupY2".ToKeyValuePair(destinationPoint.Y));
 
             UnitMakerGroupInfo? targetGroupInfo = UnitMaker.AddUnitGroup(
-                objectiveTargetUnitFamily, unitCount,
+                objectiveTargetUnitFamily, unitCount, minUnitCount, maxUnitCount,
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:152]: [issue] ref using single parameter over the two

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 8]
```diff
@@ -206,6 +216,7 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
         private void GenerateSubTask(
             DCSMission mission,
             MissionTemplateRecord template,
+            int minUnitCount, int maxUnitCount,
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:219]: [issue] ref using single parameter over the two

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 9]
```diff
@@ -284,7 +295,7 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
             }
 
             UnitMakerGroupInfo? targetGroupInfo = UnitMaker.AddUnitGroup(
-                objectiveTargetUnitFamily, unitCount,
+                objectiveTargetUnitFamily, unitCount, minUnitCount, maxUnitCount,
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:298]: [issue] ref using single parameter over the two

**Review by john681611 — CHANGES_REQUESTED** [review]
Thanks for the contribution its always appreciated.
Forgive me if this seems a bit savage of a review (I've not had a chance to review propper code in a while so I've gone for it)

Generally, there are some easy readability improvements and I'm generally trying to avoid query like calls in preference for LINQ ones as they flow way better and have half the code IMO. Otherwise like the idea.

Something we will have to do (and I'm hoping you will help out) is creating a bunch more static layouts in order to have sufficient variety that this change won't cause the same layout to be selected each time

**Comment by NovaLogicDev** [comment]
> Something we will have to do (and I'm hoping you will help out) is creating a bunch more static layouts in order to have sufficient variety that this change won't cause the same layout to be selected each time

Is there any trick to creating these? I'm pretty good at programming, horrible at the Mission Editor.

**Comment by john681611** [comment]
This file if you can get lua going.
https://github.com/akaAgar/briefing-room-for-dcs/blob/main/dataExtractors/UnitTemplateExtractor.lua

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 10]
```diff
@@ -72,6 +72,9 @@ protected override bool OnLoad(string iniFilePath)
             UnitCategory category = families.First().GetUnitCategory();
             bool allowDifferentUnitTypes = false;
 
+            // Select a list of units by country that fits the given parameters
+            var validUnits = SelectValidUnits(families, decade, unitMods); //NOTE: I moved this up here so I can do more work with the switch statement
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:76]: [nitpick] comment not needed here as self explanatory

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 11]
```diff
@@ -81,7 +84,10 @@ protected override bool OnLoad(string iniFilePath)
                     break;
                 // Units are ships or static buildings, only one unit per group (that's the law in DCS World, buddy)
                 case UnitCategory.Ship:
+                    count = 1;
+                    break;
                 case UnitCategory.Static:
+                    validUnits = countMinMax.HasValue ? LimitValidUnitsByRequestedUnitCount(countMinMax.Value, validUnits): validUnits;
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:90]: [praise] much cleaner!

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 12]
```diff
@@ -120,20 +123,62 @@ protected override bool OnLoad(string iniFilePath)
...
+                    countMinTemp -= 1;
+                }
+                while (!(validUnitsGroupSizeBetweenMinAndMax[country].Count > 0));
+
+            }
+
+            if (validUnitsGroupSizeBetweenMinAndMax.Count > 0)
+                return validUnitsGroupSizeBetweenMinAndMax;
+
+            BriefingRoom.PrintToLog($"No Units found that exceed requested TargetCount", LogMessageErrorLevel.Error);
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:158]: [nitpick] no need for this log

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 13]
```diff
@@ -120,20 +123,62 @@ protected override bool OnLoad(string iniFilePath)
...
+            throw new BriefingRoomException("Requested Target Count greater than Maximum Configured Target Count");
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:159]: [suggesion] switch this round so its if error and default returns

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 14]
```diff
@@ -120,20 +123,62 @@ protected override bool OnLoad(string iniFilePath)
...
+                        .Where(
+                            unitID => LimitValidUnitsByMinMax(
+                                validUnitsDCSIDsLengths[country].Where(unit => unit.ID == unitID).First(),
+                                countMinTemp,
+                                countMinMax.Max))
+                        .ToList();
+                    if (countMinTemp < 1) break; // if min units is now 0 and we still have no units, then an error is needed
+                    countMinTemp -= 1;
+                }
+                while (!(validUnitsGroupSizeBetweenMinAndMax[country].Count > 0));
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:151]: [suggesion] with the added units I don't think we will need this logic to reduce the minimum. Just filter down to what is valid and throw an error if for some reason we have nothing.

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs [hunk 15]
```diff
@@ -120,20 +123,62 @@ protected override bool OnLoad(string iniFilePath)
...
+                validUnitsDCSIDsLengths[country] = Database.GetEntries<DBEntryUnit>(validUnits[country].ToArray()).ToList();
+
+                // check if the list of units can satisfy the min/max requirement
+                int countMinTemp = countMinMax.Min;
+                do
+                {
+                    validUnitsGroupSizeBetweenMinAndMax[country] = validUnits[country]
+                        .Where(
+                            unitID => LimitValidUnitsByMinMax(
+                                validUnitsDCSIDsLengths[country].Where(unit => unit.ID == unitID).First(),
```
Comment (john681611) [inline Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:144]: [suggesion] just move this line into LimitValidUnitsByMinMax

File: Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs [hunk 16]
```diff
@@ -92,13 +92,17 @@ internal MissionGeneratorObjectives(UnitMaker unitMaker, DrawingMaker drawingMak
...
+            var unitCountMinMax = targetDB.UnitCount[(int)objectiveTemplate.TargetCount];
             var objectiveTargetUnitFamily = Toolbox.RandomFrom(targetDB.UnitFamilies);
+            
+            
             if (AIRBASE_LOCATIONS.Contains(targetBehaviorDB.Location) && targetDB.UnitCategory.IsAircraft())
                 objectiveCoordinates = PlaceInAirbase(template, situationDB, playerAirbase, extraSettings, targetDB, targetBehaviorDB, ref luaUnit, objectiveCoordinates, unitCount, objectiveTargetUnitFamily);
 
             UnitMakerGroupFlags groupFlags = 0;
+
+            // Set whether or not the Objective is Hidden.. options: Never OR Always
```
Comment (john681611) [inline Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs:105]: [nitpick] comment not needed here as code should be clear enough.

**Review by john681611 — CHANGES_REQUESTED** [review]
Few minor things but much better.

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs (hunk 11 above)
Comment (NovaLogicDev) [reply Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:90]: yeah, indeed. I'm kicking myself I missed this first go around.

File: Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs (hunk 14 above)
Comment (NovaLogicDev) [reply Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:151]:
```C#
                do
                {
                    if (countMinTemp < countMinMax.Max) BriefingRoom.PrintToLog("Minimum Target Count is lower than requested!", LogMessageErrorLevel.Warning);
                    validUnitsGroupSizeBetweenMinAndMax[country] ....
```
Something like this potentially?

Comment (john681611) [reply Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:151]: Seems sensible. Advantage of open source software is people are free to mess with it but they can't blame you when they break it :D

Comment (NovaLogicDev) [reply Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs:151]: Agreed, I'll implement and send in the rest of the updates.

**Review by john681611 — APPROVED** [review]
